#server:
#    port: 8080

#logging:
#    level:
#        root: info
---
spring:
    config:
        activate:
            on-profile: local

server:
  tomcat:
      threads:
          max: 1
---
spring:
    config:
        activate:
            on-profile: blackBoxServer
server:
    tomcat:
        threads:
            max: 2
            min-spare: 2
        accept-count: 2
        max-connections: 2
        connection-timeout: 1000